"""add review

Revision ID: 036ab6edc5e8
Revises: 9de761766ecf
Create Date: 2025-09-03 11:05:44.733883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '036ab6edc5e8'
down_revision: Union[str, Sequence[str], None] = '9de761766ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('review', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('movie_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['movie_uid'], ['movies.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('movies', 'director',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'released_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.alter_column('movies', 'released_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'director',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_table('review')
    # ### end Alembic commands ###
