"""Add Review db

Revision ID: 14c23118b96b
Revises: ab09fe7e9878
Create Date: 2025-09-03 10:18:06.952221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '14c23118b96b'
down_revision: Union[str, Sequence[str], None] = 'ab09fe7e9878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('review', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('movie_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['movie_uid'], ['movies.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
