"""add Category

Revision ID: 6341fa0b51f7
Revises: a9fb6590626a
Create Date: 2025-09-03 14:24:30.381406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6341fa0b51f7'
down_revision: Union[str, Sequence[str], None] = 'a9fb6590626a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_categories_genre'), 'categories', ['genre'], unique=False)
    op.add_column('movies', sa.Column('category_uid', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_movies_category_uid'), 'movies', ['category_uid'], unique=False)
    op.create_foreign_key(None, 'movies', 'categories', ['category_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_index(op.f('ix_movies_category_uid'), table_name='movies')
    op.drop_column('movies', 'category_uid')
    op.drop_index(op.f('ix_categories_genre'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
