"""add user review fk

Revision ID: 8d8c93976411
Revises: 036ab6edc5e8
Create Date: 2025-09-03 13:34:23.376343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d8c93976411'
down_revision: Union[str, Sequence[str], None] = '036ab6edc5e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_uid', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'review', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'user_uid')
    # ### end Alembic commands ###
