"""Change foregin key to movie_title

Revision ID: 9de761766ecf
Revises: 14c23118b96b
Create Date: 2025-09-03 10:28:57.582943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9de761766ecf'
down_revision: Union[str, Sequence[str], None] = '14c23118b96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('movie_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('review_movie_uid_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'movies', ['movie_title'], ['title'])
    op.drop_column('review', 'movie_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('movie_uid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_movie_uid_fkey'), 'review', 'movies', ['movie_uid'], ['uid'])
    op.drop_column('review', 'movie_title')
    # ### end Alembic commands ###
