"""init

Revision ID: ab09fe7e9878
Revises: 
Create Date: 2025-08-28 15:59:48.709784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab09fe7e9878'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('movies', 'director',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'released_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'released_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'director',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
